// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package codegen

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	Email           string
	Password        string
	IsEmailVerified bool
	AvatarUrl       *string
}
