services:
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis7
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
volumes:
  psql_volume:
  redis_volume:
