// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restaurant_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addRestaurantUser = `-- name: AddRestaurantUser :exec
INSERT INTO restaurant_users (user_id, restaurant_id, role_id)
VALUES ($1, $2, $3)
`

type AddRestaurantUserParams struct {
	UserID       uuid.UUID
	RestaurantID uuid.UUID
	RoleID       int16
}

func (q *Queries) AddRestaurantUser(ctx context.Context, arg AddRestaurantUserParams) error {
	_, err := q.db.Exec(ctx, addRestaurantUser, arg.UserID, arg.RestaurantID, arg.RoleID)
	return err
}
